/**
 * Country → search languages for the SERP preview tab (pure data, no DOM).
 *
 * Values are Google `hl` codes (ISO 639-1, plus Google's variants: `zh-CN`,
 * `zh-TW`, `zh-HK`, `pt-BR`, `pt-PT`, legacy `iw` for Hebrew, `fil`).
 * The FIRST entry is the default language suggested for that country.
 * Covers every ISO2 in countries.v1.json (asserted by test/serp.test.ts).
 */

export const COUNTRY_LANGS: Record<string, string[]> = {
  AD: ['ca', 'es', 'fr'],
  AE: ['ar', 'en'],
  AF: ['fa', 'ps'],
  AG: ['en'],
  AI: ['en'],
  AL: ['sq'],
  AM: ['hy', 'ru'],
  AO: ['pt'],
  AR: ['es'],
  AS: ['en'],
  AT: ['de'],
  AU: ['en'],
  AW: ['nl', 'es'],
  AX: ['sv'],
  AZ: ['az', 'ru'],
  BA: ['bs', 'hr', 'sr'],
  BB: ['en'],
  BD: ['bn'],
  BE: ['nl', 'fr', 'de'],
  BF: ['fr'],
  BG: ['bg'],
  BH: ['ar', 'en'],
  BI: ['fr', 'en'],
  BJ: ['fr'],
  BL: ['fr'],
  BM: ['en'],
  BN: ['ms', 'en'],
  BO: ['es'],
  BQ: ['nl'],
  BR: ['pt-BR'],
  BS: ['en'],
  BT: ['en'],
  BV: ['no'],
  BW: ['en'],
  BY: ['ru', 'be'],
  BZ: ['en', 'es'],
  CA: ['en', 'fr'],
  CC: ['en'],
  CD: ['fr'],
  CF: ['fr'],
  CG: ['fr'],
  CH: ['de', 'fr', 'it'],
  CI: ['fr'],
  CK: ['en'],
  CL: ['es'],
  CM: ['fr', 'en'],
  CN: ['zh-CN'],
  CO: ['es'],
  CR: ['es'],
  CU: ['es'],
  CV: ['pt'],
  CW: ['nl', 'en'],
  CX: ['en'],
  CY: ['el', 'en', 'tr'],
  CZ: ['cs'],
  DE: ['de'],
  DJ: ['fr', 'ar'],
  DK: ['da'],
  DM: ['en'],
  DO: ['es'],
  DZ: ['ar', 'fr'],
  EC: ['es'],
  EE: ['et', 'ru'],
  EG: ['ar', 'en'],
  EH: ['ar'],
  ER: ['en', 'ar'],
  ES: ['es', 'ca'],
  ET: ['am', 'en'],
  FI: ['fi', 'sv'],
  FJ: ['en'],
  FK: ['en'],
  FM: ['en'],
  FO: ['da'],
  FR: ['fr'],
  GA: ['fr'],
  GB: ['en'],
  GD: ['en'],
  GE: ['ka', 'ru'],
  GF: ['fr'],
  GG: ['en'],
  GH: ['en'],
  GI: ['en', 'es'],
  GL: ['da'],
  GM: ['en'],
  GN: ['fr'],
  GP: ['fr'],
  GQ: ['es', 'fr', 'pt'],
  GR: ['el'],
  GS: ['en'],
  GT: ['es'],
  GU: ['en'],
  GW: ['pt'],
  GY: ['en'],
  HK: ['zh-HK', 'en'],
  HM: ['en'],
  HN: ['es'],
  HR: ['hr'],
  HT: ['fr', 'ht'],
  HU: ['hu'],
  ID: ['id'],
  IE: ['en', 'ga'],
  IL: ['iw', 'en', 'ru'],
  IM: ['en'],
  IN: ['hi', 'en'],
  IO: ['en'],
  IQ: ['ar', 'en'],
  IR: ['fa'],
  IS: ['is'],
  IT: ['it'],
  JE: ['en'],
  JM: ['en'],
  JO: ['ar', 'en'],
  JP: ['ja'],
  KE: ['en', 'sw'],
  KG: ['ky', 'ru'],
  KH: ['km', 'en'],
  KI: ['en'],
  KM: ['fr', 'ar'],
  KN: ['en'],
  KP: ['ko'],
  KR: ['ko'],
  KW: ['ar', 'en'],
  KY: ['en'],
  KZ: ['ru', 'kk'],
  LA: ['lo', 'en'],
  LB: ['ar', 'fr', 'en'],
  LC: ['en'],
  LI: ['de'],
  LK: ['si', 'ta', 'en'],
  LR: ['en'],
  LS: ['en', 'st'],
  LT: ['lt', 'ru'],
  LU: ['fr', 'de'],
  LV: ['lv', 'ru'],
  LY: ['ar'],
  MA: ['ar', 'fr'],
  MC: ['fr'],
  MD: ['ro', 'ru'],
  ME: ['sr'],
  MF: ['fr'],
  MG: ['fr', 'mg'],
  MH: ['en'],
  MK: ['mk'],
  ML: ['fr'],
  MM: ['my', 'en'],
  MN: ['mn'],
  MO: ['zh-TW', 'pt'],
  MP: ['en'],
  MQ: ['fr'],
  MR: ['ar', 'fr'],
  MS: ['en'],
  MT: ['mt', 'en'],
  MU: ['en', 'fr'],
  MV: ['en'],
  MW: ['en'],
  MX: ['es'],
  MY: ['ms', 'en'],
  MZ: ['pt'],
  NA: ['en'],
  NC: ['fr'],
  NE: ['fr'],
  NF: ['en'],
  NG: ['en'],
  NI: ['es'],
  NL: ['nl'],
  NO: ['no'],
  NP: ['ne', 'en'],
  NR: ['en'],
  NU: ['en'],
  NZ: ['en'],
  OM: ['ar', 'en'],
  PA: ['es'],
  PE: ['es'],
  PF: ['fr'],
  PG: ['en'],
  PH: ['en', 'fil'],
  PK: ['ur', 'en'],
  PL: ['pl'],
  PM: ['fr'],
  PN: ['en'],
  PR: ['es', 'en'],
  PS: ['ar'],
  PT: ['pt-PT'],
  PW: ['en'],
  PY: ['es'],
  QA: ['ar', 'en'],
  RE: ['fr'],
  RO: ['ro'],
  RS: ['sr'],
  RU: ['ru'],
  RW: ['en', 'fr'],
  SA: ['ar'],
  SB: ['en'],
  SC: ['en', 'fr'],
  SD: ['ar', 'en'],
  SE: ['sv'],
  SG: ['en', 'zh-CN', 'ms', 'ta'],
  SH: ['en'],
  SI: ['sl'],
  SJ: ['no'],
  SK: ['sk'],
  SL: ['en'],
  SM: ['it'],
  SN: ['fr'],
  SO: ['so', 'ar'],
  SR: ['nl'],
  SS: ['en'],
  ST: ['pt'],
  SV: ['es'],
  SX: ['nl', 'en'],
  SY: ['ar'],
  SZ: ['en'],
  TC: ['en'],
  TD: ['fr', 'ar'],
  TF: ['fr'],
  TG: ['fr'],
  TH: ['th'],
  TJ: ['tg', 'ru'],
  TK: ['en'],
  TL: ['pt', 'id'],
  TM: ['tk', 'ru'],
  TN: ['ar', 'fr'],
  TO: ['en'],
  TR: ['tr'],
  TT: ['en'],
  TV: ['en'],
  TW: ['zh-TW'],
  TZ: ['sw', 'en'],
  UA: ['uk', 'ru'],
  UG: ['en', 'sw'],
  UM: ['en'],
  US: ['en', 'es'],
  UY: ['es'],
  UZ: ['uz', 'ru'],
  VA: ['it'],
  VC: ['en'],
  VE: ['es'],
  VG: ['en'],
  VI: ['en'],
  VN: ['vi'],
  VU: ['en', 'fr'],
  WF: ['fr'],
  WS: ['en'],
  XK: ['sq', 'sr'],
  YE: ['ar'],
  YT: ['fr'],
  ZA: ['en', 'af', 'zu'],
  ZM: ['en'],
  ZW: ['en'],
};
